apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc-app
  namespace: app-ns
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
volumeBindingMode: Immediate
