apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-vol
  namespace: app-ns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 20Gi